content/assets/stylesheets/includes/navbar.scss
=> Align search

content/robots.txt
Disallows search engines (and other crawlers) from indexing our wiki. Some users probably do not want our wiki to be the first result when their username is googled.
=> Disallow /wiki/ in robots.txt

content/about/contact.erb
Using @ugent.be instead of .ugent.be
=> Fixed typo in contact page

content/cammie.erb
In https://github.com/ZeusWPI/zeus.ugent.be/commit/0c6307971ad5f424bab0bc25128e92dcb2738398, JQuery is no longer default enabled on all pages. Since Cammie needed JQuery, it broke and could no longer move.
=> Fix cammie JQuery

.travis.yml
This flag should make git use the latest commit from the branch specified in the .gitmodules file when checking out the subrepositories.
This way, nobody has to remember to manually update the drive, like in 55fc57d9db7309100c81323e737bc2e9c05ab14c.
On the other hand, it would be possible to break the site build by pushing garbage to the drive repo, so that's something to consider.
=> Use the latest commit for submodules

layouts/partials/_map.erb
Explanation available on <https://photon.komoot.io>
>Note:
Until October 2020 the API was available under photon.komoot.de. Requests still work as they redirected to photon.komoot.io but please update your apps accordingly.
=> update photon link to https://photon.komoot.io

Gemfile, Gemfile.lock, Rules, layouts/blogpost.erb, lib/data_sources/katex.rb, nanoc.yaml
This PR adds support for math symbols, which is something I hope to use in the future on the Zeus site. Cool thing about Katex is that it renders the math symbols server side, only needing a bit of css. Unlike Mathjax, no javascript is required.
=> Add Katex (Math mode) support

layouts/partials/_events_tile.erb
See #286 for screenshot of previous issue.
=> reduce size of titles and text when mobile, fixes #286

Rules, content/assets/stylesheets/includes/general.scss, lib/data_sources/katex.rb
Forgot adding some fonts for the math mode I added earlier. It looks a lot nicer now!
=> Fix KaTeX (math mode) fonts

content/blog/20-21/archief.md
Use normal links instead of using the items, which don't exist in dev mode.
=> Fix compiling in dev mode

.github/workflows/master.yml, .github/workflows/pr.yml
should make the new builds faster in CI.
It uses the cache from master when building for the first time for a PR
=> feat(ci): add caching for the output folder generated by nandoc

layouts/default.erb
Context from the nanoc issue (https://github.com/nanoc/nanoc/issues/1642)
> At Zeus WPI (:wave:  @denisdefreyne), we run our site on multiple domains: both on zeus.ugent.be and zeus.gent. We also have `<number>`.pr.zeus.gent, which deploys previews of pull requests against the site repository. When searching content on for example Google, both zeus.gent and zeus.ugent.be show up, diluting search results. A (standardized) way to prevent duplicate content is [the canonical link element](https://en.wikipedia.org/wiki/Canonical_link_element).
=> Set link canonical property to zeus.ugent.be

content/assets/stylesheets/main.scss
As an example:
old:
new:
I haven't found a place where the hyphen behavior is desired; but even if somewhere on the site this is wanted, we could add it with a narrower scope than 'the entire body'
=> Remove auto hyphens from body

content/index.erb, lib/helpers/blog.rb, lib/helpers/time.rb
fixes #584
titles are clickable
new helper method in blog.rb -> not sure if this is a good place
-> so you don't have to update the links every academic year
=> Make titles clickable

content/blog/23-24/esp32-reverse-engineering-continued.md
Link to the previous blogpost was broken (you could also do this with nanoc helpers to make it dynamic, but might be unnecessary.)
=> Fix broken link

content/well-known/security.txt
According to https://www.rfc-editor.org/rfc/rfc9116#name-policy, the Policy field can appear multiple times (see for example "Preferred-Languages" where it is explicitly mentioned it must only appear once)
Depends on https://git.zeus.gent/ZeusWPI/drive/pulls/146/files to be merged
=> Add english version of responsible disclosure policy

layouts/tiles/blokmap.erb
This makes it fullwidth again.
=> Update blokmap tile to fit the current form of the frontage

lib/helpers/ical.rb
Some calendar applications are dumb and only identify events by UID.
This causes some sync solutions to add more events instead replacing the existing ones
These UIDs were not persistent across builds of the site.
=> Make ical UID more consistent

content/assets/stylesheets/includes/tiles.scss, layouts/tiles/blokmap.erb
On mobile, blokmap tile looks pretty bad, this should change that
Example:
=> Change blokmap tile to be more responsive

layouts/partials/_navbar.erb
URL where it's loaded from is localhost for now, until the new subdomain is running
=> zapp button in header
