ZeusWPI/zeus.ugent.be

content/assets/stylesheets/includes/tiles.scss
content/assets/stylesheets/includes/variables.scss
content/assets/stylesheets/main.scss
content/index.erb
layouts/partials/_tile.erb

Make layout prettier. Small issue with link highlights.

prettier index

---

content/cammie.erb

Use buttons for absolute navigation

---

Rules

fix autoprefixer

---

content/assets/stylesheets/includes/general.scss
layouts/partials/_navbar.erb

smaller yet equal spacing between and around social icons

---

content/assets/stylesheets/includes/general.scss

make tab hover underline as heigh as the select underline

---

Gemfile
Gemfile.lock
Rules
content/assets/stylesheets/includes/eventpage.scss
content/assets/stylesheets/includes/general.scss
content/events/16-17/LAN.md
content/events/16-17/datacenter.md
content/events/16-17/lip.md
layouts/default.erb
layouts/eventpost.erb
layouts/partials/_event_preview.erb
layouts/partials/_footer.erb
lib/helpers/font_awesome.rb
lib/helpers/ical.rb

Geeks, Attack! V

---

Gemfile
Gemfile.lock
Rules
content/assets/stylesheets/includes/blogpost.scss
content/posts/16-17/bestuur.md
content/posts/16-17/inkscape.md
layouts/blogpost.erb

Adding an author field in the metadata of a blogpost, will render it below the title as follows

Authors, fixes #53

---

content/index.erb

Past events display as such

---

content/assets/stylesheets/includes/cammie.scss

- instead of _

---

README.md

Could be incomplete/wrong for some tags. @werthen fix where needed

Update meta-tags info

---

content/about.erb

Fixed uncorrectly formatted html

---

content/assets/stylesheets/includes/navbar.scss
layouts/partials/_navbar.erb

Implement #43

---

content/assets/stylesheets/includes/general.scss
content/assets/stylesheets/includes/tiles.scss
content/index.erb
layouts/tiles/blokmap.erb

work on blokmap

---

content/assets/stylesheets/includes/eventpage.scss
content/events/16-17/hashcode.md
layouts/eventpost.erb
lib/helpers/events.rb

Ik ben niet zo tevreden met de hero. Hebben we een optie om de tekst zwart te maken?

Add Hashcode event

---

content/about/about.erb
content/about/contact.erb
content/assets/stylesheets/includes/about.scss
content/assets/stylesheets/includes/general.scss
content/assets/stylesheets/includes/tiles.scss
content/assets/stylesheets/main.scss

PREVIEW LINK: http://198.zeus.werthen.com
Before:
After:
After really:

Revamp contact

---

content/assets/stylesheets/includes/eventpage.scss
content/assets/stylesheets/includes/navbar.scss
content/assets/stylesheets/main.scss
layouts/eventpost.erb
layouts/partials/_navbar.erb

Fix transparent menu on smaller screens

---

.travis.yml
Gemfile
Gemfile.lock
README.md
Rules
content/about/verslagen.erb
content/about/verslagen/17-18/2017-11-20.md
content/about/verslagen/17-18/2018-02-12.md
layouts/partials/_about_sub_navbar.erb
lib/filters/pandoc_pdf.rb
lib/helpers/preprocess.rb
lib/helpers/reports.rb
lib/helpers_.rb

Reports should start analogous to the following format:
```
% Bestuursvergadering 3
% Isaura Claeys
% 21/02/2018 - 17:25
```
See https://pandoc.org/MANUAL.html#metadata-blocks
I don't immediately see a way to make YAML metadata blocks work, as nanoc immediately interprets them.

Reports (only includes latest report as well)

---

content/blog/17-18/cscbe.md

Link to other writeup

---

content/blog/17-18/cscbe.md

Turned out @nudded 's comment about  key scrambling wasn't relevant, I just brainfarted.

Fix explanation

---

content/blog/17-18/update-maart.md

Cool stuff! Here are a few minor suggestions.

March update corrections / suggestions

---

content/events/17-18/lightning-talks.md

Creating a pull request to view result

added lightning talks event

---

content/events/17-18/zeus-kiest.md

Zeus Kiest 2018

---

content/about/statuten.md

Fixed wrong numbering

---

content/about/verslagen/17-18/2018-04-19.md

De discussiepunten kunnen nog wat beter herschreven worden, ik heb momenteel wat minder tijd.

[WIP] Vergadering 19/04/2018

---

content/blog/17-18/state-of-the-wpi.md

A recap of the year 2017-2018 of Zeus WPI.
Please tell me if I forgot to mention things.

State of the WPI

---

.travis.yml
content/blog/18-19/chat.md
lib/helpers/preprocess.rb

Preview on <http://263.pr.zeus.gent/blog/18-19/chat/>

Chat blogpost

---

content/events/18-19/datacenter.md

Added Datacenter event

---

content/assets/stylesheets/includes/about.scss

Fixed mobile styling for table

---

content/about/contact.erb

I have not been able to run it on my system, but I didn't really change anything other than text.

Changed Slack link to Mattermost link

---

content/projects/mozaic.md

Fixes #262 fix faulty redirect to mozaic github

---

content/about/contact.erb
layouts/eventpost.erb
layouts/partials/_map.erb

Replaced Google maps embed on about:contact page with openstreetmap

---

content/index.erb

Open Graph is neat and works with Mattermost previews

Add Open Graph tags

---

content/events/18-19/ctf.md

Added Capture The Friday

---

content/blog/18-19/g2_blogpost.md

A blogpost about the upcoming G2 project

G2 blogpost

---

content/events/18-19/verkiezingen.md

Added verkiezingen 2019

---

content/blog/18-19/bestuur-19-20.md

Totaal niet gestolen van vorig jaar, dank @werthen

Bestuur '19-'20

---

content/assets/images/Logos_Blokmap.svg

rounded corners blokmap icon

---

layouts/events.erb
layouts/partials/_soon_tile.erb
lib/helpers/events.rb
lib/helpers/ical.rb
lib/helpers/preprocess.rb

- Fix merge
- Some HTML improvements:
- Use partial instead of inline tile
- Correct background colour if event has none
- Don't use `<i>` tag, use `<em>`
- Use UTF8 ™ instead of TM
- Don't put "soon" events in the ical

Fixes for events/soon

---

content/robots.txt

There seems to be no robots.txt standard, though, so I've no idea if this works.

Allow less crawling

---

layouts/eventpost.erb

Don't hide everything if there is no locationlink

---

content/events/19-20/godot.md

WIP: Re-add godot event

---

content/about/privacy.erb
content/about/privacy/blokmap.md
content/about/privacy/mattermore.md
content/about/privacy/mattermost.md
content/about/privacy/site.md

- Indicate Crashlytics is from Google
- Correct wrong term

Improvements to privacy policy

---

content/about/sponsorende-leden.erb
content/blog/20-21/bestuur20_21.md
data/bestuur.yaml
data/supporting_members.yaml
lib/helpers/about.rb
nanoc.yaml

Heads-up: ik heb ook het academiejaar moeten aanpassen om het nieuw bestuur te tonen, daarom zijn sponsorende leden nu ook leeg.

Bestuur 20-21

---

Rules
content/blog/19-20/corona.md
content/blog/19-20/vleor.md
content/blog/20-21/bestuur20_21.md
content/blog/20-21/wij-coden-voort.md
layouts/blogs.erb
lib/helpers/archives.rb
lib/helpers/preprocess.rb

Add's tags to blog posts.
Closes #111

Add tags filter to blog posts

---

data/supporting_members.yaml

As requested by @redfast00. Feel free to remove the gravatar link with a zeuswpi link, I just dont have the credentials to upload.

add me as a sponsor

---

layouts/blogpost.erb
lib/helpers/blog.rb
lib/helpers/preprocess.rb

Reverts ZeusWPI/zeus.ugent.be#409

Revert "added helper function to get modification time from git"

---

shell.nix

This is of course something OS-specific, so I would understand if you would not want to bloat the repository with this.

Add shell.nix for easy development with nix

---

Gemfile
Gemfile.lock
gemset.nix
shell.nix

So you don't need to use `bundle` to install gems. Also add terminal-notifier when using macos

Use bundix for nixos-shell, and enhancements for darwin

---

content/events/20-21/210_game_jam_ludum_dare.md
content/events/20-21/220_lightning_talks_at_home_edition.md

It is a bit more useful to make links clickable.

Add links to gamejam event

---

data/supporting_members.yaml

fix silivus

---

.travis.yml

Upgrade ubuntu dist on Travis

---

content/cammie.erb

Impressive that even the door moved a bit

Update cammie coords after keldermeubelherordening

---

content/events/21-22/320_barbecue_studententuin.md

Add barbecue event

---

content/about/about.erb
content/blog/17-18/tech-talkz.md
content/events/17-18/internet-freedom.md
content/index.erb

As per https://twitter.com/Senficon/status/1486293287938015235

Use changed name and pronouns of Felix Reda

---

content/events/22-23/lan.md
content/events/22-23/nerf.md

Waiting for a fix in gandalf to be able to update this link.

Nerf event + Lan :tm: 

---

content/assets/scripts/tabtopup.js

add username prefill

---

.github/workflows/pr.yml

Hopefully speeds up the deploy CI action for a PR

refactor(actions): replace sftp with rsync

---

content/assets/stylesheets/includes/tiles.scss

I know it's a bit silly for 1 line but I wanted a preview so it people can see the change before we merge it into master

style(tiles): fill background image of tile

---

content/events/21-22/01_potluck.md
content/events/21-22/03_spelletjesavond.md
content/events/21-22/230_verkiezingen.md
content/events/21-22/320_barbecue_studententuin.md
lib/helpers/preprocess.rb

Add location links for studententuin

---

content/assets/scripts/message.js
content/cammie.erb

something wrong with the CORS headers still

Add a username field where you can enter a username to be displayed on

---

content/events/22-23/nix-party.md

Create an event for the nix.party we're gonna throw.

add nix.party event

---

content/events/22-23/foxhunt.md
content/events/22-23/verkiezingen.md

Zie onderaan https://codimd.zeus.gent/aClDhgjaRKecj5_6-XDZSA#Events

Switch foxhunt en verkiezingen

---

content/contact.erb
data/supporting_members.yaml
layouts/banner.erb
layouts/default.erb
layouts/eventpost.erb
layouts/partials/_events_tile.erb
lib/helpers/font_awesome.rb
nanoc.yaml

Everyone that was sponsor in 2022 an also in 2023 is copied over. I'll wait a few more days so they can still ask to change or remove things (I DM'ed them).

Sponsoring members of 2023

---

content/cammie.erb
content/events/23-24/verkiezingen.md

Herverkiezingen event toegevoegd

---

content/events/23-24/skireis.md

Ceneka heeft wat informatie geupdate.
Ze gaan ons op de hoogte houden bij inschrijvingen dus geen nood aan ski@zeus.ugent.be

Update ski info

---

content/blog/23-24/additional_problems.md

- Operator precedence of %
- Some minor typographical things

Minor suggestions to latest blogpost

---

content/events/23-24/10ul.md

Apparently the 10 ul is a day earlier

10 ul wrong date

---

data/supporting_members.yaml
nanoc.yaml

Update member sponsors for 2024

new member sponsors

---

data/supporting_members.yaml

Er stonden wat outdated dingen in

Update van chvp in supporting_members

---

Gemfile
Gemfile.lock
README.md
gemset.nix
lib/filters/htmlpress.rb
packages.nix

docs(README): Document changing dependencies with nix.
build(nix): Add bundix package to nix-shell.
fix(js): Replace uglier compressor with terser, adding ES6 support.

fix(js): Replace uglier compressor with terser, adding ES6 support.
